server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sehwan-Jang/msa-cloud-config.git
          username: Sehwan-Jang
          password: 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
        native:
          search-locations: file:///C:/Users/DIR-N-151/Documents/projects/git-local-repo
  profiles:
    active: native

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, busenv